sudo: required
services:
  - docker

before_install:
  - docker pull rgrpc/grpc_dev:stable

script:
  - >
    docker run -v `pwd`:/grpc rgrpc/grpc_dev:stable /bin/bash -c "
    cd /tmp &&
    R CMD INSTALL /grpc && 
    Rscript --vanilla -e \"testthat::test_package('grpc')\"
    "
