// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fetch
RawVector fetch(CharacterVector server, CharacterVector method, RawVector requestArg, CharacterVector metadata, bool useTLS, CharacterVector CertPath, CharacterVector AccessToken, int ClientDeadline);
RcppExport SEXP _grpc_fetch(SEXP serverSEXP, SEXP methodSEXP, SEXP requestArgSEXP, SEXP metadataSEXP, SEXP useTLSSEXP, SEXP CertPathSEXP, SEXP AccessTokenSEXP, SEXP ClientDeadlineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type server(serverSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< RawVector >::type requestArg(requestArgSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type metadata(metadataSEXP);
    Rcpp::traits::input_parameter< bool >::type useTLS(useTLSSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type CertPath(CertPathSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type AccessToken(AccessTokenSEXP);
    Rcpp::traits::input_parameter< int >::type ClientDeadline(ClientDeadlineSEXP);
    rcpp_result_gen = Rcpp::wrap(fetch(server, method, requestArg, metadata, useTLS, CertPath, AccessToken, ClientDeadline));
    return rcpp_result_gen;
END_RCPP
}
// grpc_version
CharacterVector grpc_version();
RcppExport SEXP _grpc_grpc_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(grpc_version());
    return rcpp_result_gen;
END_RCPP
}
// run
List run(List target, CharacterVector hoststring, List hooks, bool useTLS, CharacterVector CertPath, CharacterVector AccessToken);
RcppExport SEXP _grpc_run(SEXP targetSEXP, SEXP hoststringSEXP, SEXP hooksSEXP, SEXP useTLSSEXP, SEXP CertPathSEXP, SEXP AccessTokenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type target(targetSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type hoststring(hoststringSEXP);
    Rcpp::traits::input_parameter< List >::type hooks(hooksSEXP);
    Rcpp::traits::input_parameter< bool >::type useTLS(useTLSSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type CertPath(CertPathSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type AccessToken(AccessTokenSEXP);
    rcpp_result_gen = Rcpp::wrap(run(target, hoststring, hooks, useTLS, CertPath, AccessToken));
    return rcpp_result_gen;
END_RCPP
}
