// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fetch
RawVector fetch(CharacterVector server, CharacterVector method, RawVector requestArg, CharacterVector metadata, int client_deadline);
RcppExport SEXP _grpc_fetch(SEXP serverSEXP, SEXP methodSEXP, SEXP requestArgSEXP, SEXP metadataSEXP, SEXP client_deadlineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type server(serverSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< RawVector >::type requestArg(requestArgSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type metadata(metadataSEXP);
    Rcpp::traits::input_parameter< int >::type client_deadline(client_deadlineSEXP);
    rcpp_result_gen = Rcpp::wrap(fetch(server, method, requestArg, metadata, client_deadline));
    return rcpp_result_gen;
END_RCPP
}
// grpc_version
CharacterVector grpc_version();
RcppExport SEXP _grpc_grpc_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(grpc_version());
    return rcpp_result_gen;
END_RCPP
}
// run
List run(List target, CharacterVector hoststring, List hooks);
RcppExport SEXP _grpc_run(SEXP targetSEXP, SEXP hoststringSEXP, SEXP hooksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type target(targetSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type hoststring(hoststringSEXP);
    Rcpp::traits::input_parameter< List >::type hooks(hooksSEXP);
    rcpp_result_gen = Rcpp::wrap(run(target, hoststring, hooks));
    return rcpp_result_gen;
END_RCPP
}
