# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
grpc_version <- function() {
    .Call('grpc_grpc_version', PACKAGE = 'grpc')
}

run <- function(target) {
    .Call('grpc_run', PACKAGE = 'grpc', target)
}

